@baseUrl = http://localhost:3333
@authToken = {{ authenticate.response.body.access_token }}

# =========================================================
# AUTH
# =========================================================

# @name authenticate
POST {{ baseUrl }}/sessions
Content-Type: application/json

{
  "cpf": "234.205.000-33",
  "password": "123456"
}

###

# =========================================================
# CREATE RECIPIENT
# =========================================================

# @name create_order
POST {{ baseUrl }}/orders
Authorization: Bearer {{ authToken }}
Content-Type: application/json

{
  "recipientId": "{{ recipientId }}",
  "deliveryAddress": {
    "street": "Rua das Flores",
    "number": "123",
    "complement": "Casa",
    "neighborhood": "Centro",
    "city": "Campo Mourão",
    "state": "PR",
    "zipCode": "87300000",
    "latitude": -24.0462,
    "longitude": -52.3781
  },
  "postedAt": "2026-02-18T14:30:00.000Z"
}

###

# =========================================================
# UPDATE ORDER
# =========================================================

PATCH {{ baseUrl }}/orders/{{ create_order.response.body.id }}
Authorization: Bearer {{ authToken }}
Content-Type: application/json

{
  "status": "DELIVERED",
  "deliveredAt": "2026-02-18T16:00:00.000Z"
}

###

# =========================================================
# DELETE ORDER
# =========================================================

DELETE {{ baseUrl }}/orders/{{ create_order.response.body.id }}
Authorization: Bearer {{ authToken }}

###

# =========================================================
# FETCH ORDERS
# =========================================================
GET {{ baseUrl }}/orders?page=1&status=PENDING
Authorization: Bearer {{ authToken }}

###

# =========================================================
# ASSIGN DELIVERYMAN TO ORDER
# =========================================================

PATCH {{ baseUrl }}/orders/{{ orderId }}/assign
Authorization: Bearer {{ authToken }}
Content-Type: application/json

{
  "deliverymanId": "{{ deliverymanId }}"
}
