@baseUrl = http://localhost:3333
@authToken = {{ authenticate.response.body.access_token }}

# @name register
POST {{ baseUrl }}/accounts
Content-Type: application/json

{
  "name": "Matheus",
  "cpf": "603.759.950-56",
  "password": "123456"
}

###

# @name authenticate
POST {{ baseUrl }}/sessions
Content-Type: application/json

{
  "cpf": "603.759.950-56",
  "password": "123456"
}

###

# @name fetch_users
GET {{ baseUrl }}/users?role=DELIVERYMAN
Authorization: Bearer {{ authToken }}

###

# @name update_user
PATCH {{ baseUrl }}/users/7a988776-affb-490a-b869-0778450bef73
Content-Type: application/json
Authorization: Bearer {{ authToken }}

{
  "name": "Amanda",
  "cpf": "234.205.000-33"
}

###

# @name change_user_password
PATCH {{ baseUrl }}/users/c3540ab4-39f2-4d4a-8e43-dc5fdb76e89c/password
Content-Type: application/json
Authorization: Bearer {{ authToken }}

{
  "currentPassword": "123456",
  "newPassword": "654321"
}

###

# @name change_user_role
PATCH {{ baseUrl }}/users/cd79f8ea-dd67-4640-a9fc-645f35d8d522/role
Content-Type: application/json
Authorization: Bearer {{ authToken }}

{
  "role": "ADMIN"
}
